#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
$HOME/.config/polybar/launch.sh
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           2
bspc config top_padding          27
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config split_ratio          0.50
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#ffffff"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen

#Floating applications
bspc rule -a Alacritty state=floating
bspc rule -a Termite state=floating
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
bspc rule -a Oblogout state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

nitrogen --restore &&
##xrandr --mode 1366x768
##xrandr --output HDMI1 --auto --primary --mode 1920x1080
##xrandr --output LVDS1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal
setxkbmap latam &
picom -f &

#open applications on specific workspaces
##bspc rule -a Termite desktop='^1' follow=on state=floating
##bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a Chromium desktop='^2'  follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a vlc desktop='^4'  follow=on
bspc rule -a mpv desktop='^4'  follow=on
bspc rule -a Minitube desktop='^4'  follow=on
bspc rule -a Geany desktop='^5'  follow=on
bspc rule -a Wps desktop='^5'  follow=on
bspc rule -a retroarch desktop='^6'  follow=on
bspc rule -a Gimp-2.10 desktop='^7'  follow=on
bspc rule -a Nitrogen desktop='^8'  follow=on
bspc rule -a Lxappearance desktop='^8'  follow=on
bspc rule -a TelegramDesktop desktop='^9'  follow=on
bspc rule -a Pamac-manager desktop='^10'  follow=on
#bspc rule -a Atom desktop='^9' follow=on
#bspc rule -a Deezer desktop='^10' follow=on
#bspc rule -a Steam desktop='^10'

